### PR TITLE
Fix minor typos

### PR DESCRIPTION
**Pull request by jdujava**
Just couple of things I've noticed :wink:.

### CODE REVIEW

**Comment by bakkeby** [comment]
Thanks, much appreciated. 

Can you clarify your reasoning for changing the lines regarding mouse button being pressed or being released?

It sounds odd to me. We are interested in both, not one or the other.

**Comment by jdujava** [comment]
For example, `BUTTONMASK` is simply `ButtonPressMask` or _(mathematical or)_ `ButtonReleaseMask`.

I would thus say 'we are interested in receiving events when a mouse button is either pressed or released', instead of using 'and'.

**Comment by bakkeby** [comment]
Yes but we are talking about plain English here and you are referring to `|` which is a binary or.

You wouldn't say that you are going to the store to buy apples binary or bananas if your intent is to buy both.

Likewise you wouldn't say that you are going to the store to buy either apples or bananas if your intent is to buy both.

For the `MOUSEMASK` macro I think it that quite strictly only the button release is of interest.

I'll tidy up in any case. Thanks a lot for the corrections.

**Comment by jdujava** [comment]
My understanding is that setting the `MASK` to be `ButtonPressMask|ButtonReleaseMask` means that we are interested in events corresponding to pressing the button or releasing the button, but we ignore everything else. So the analogy would be something like: I am going to the store to buy either an apple or a banana, I don't exactly know which yet (I am fine with either one), but I certainly don't want orange.

I think we are trying to say the same thing, but we are approaching it from different points of view :smile:. I would dare to say mine follows more closely the way it is implemented using _binary or_ `|`, so that's why I suggested the corresponding changes.

But anyway, I think the corrected comments are now rather clear (however, at the first read one can wonder why the comment before `MOUSEMASK` only mentions releasing, and not also pressing).

Also something I forgot before: Thank you for your amazing work!

**Comment by bakkeby** [comment]
It's a binary mask; it is used in the context to say that we are interested in getting notifications when a user clicks on a window and when a user releases the button. 

This is again combined with other flags to say that we are also interested to receive events when the mouse moves. So what you are telling the computer is that you want to be notified when the mouse moves, and you want to be notified when the user clicks on a window and you want to be notified when the user stops clicking. 

If you are saying that you want to be notified when the mouse moves, or when the user clicks, or when the user releases that click, then logically you are fine with not receiving events for all of these conditions as long as you receive a notification for at least one of these conditions.

I think we are on the same page regarding this. All the conditions won't happen at the same time. 

As for how it works in practice: dwm has bindings for button presses. It simply ignores button releases.

The only place where it is taken into account is in the movemouse and resizemouse functions, triggered by buttonpress. As such the MOUSEMASK macro is only used for tracking mouse movements and the button release so that it knows when to stop.

**Pull request merged**
